//
// Generated by Microsoft (R) D3DX9 Shader Assembler 4.09.00.1126
//
//   vsa t:\Direct3D Color Grading\shaders\screen for ps_1_1.vsh
//    /Fht:\Direct3D Color Grading\shaders\screen for ps_1_1.vsh.h /nologo
//

const DWORD g_vs11_main[] =
{
    0xfffe0101, 0x0000001f, 0x80000000, 0x900f0000, 0x0000001f, 0x80000003, 
    0x900f0001, 0x0000001f, 0x80000005, 0x900f0002, 0x00000051, 0xa00f0004, 
    0x3f800000, 0x3f000000, 0x00000000, 0x40000000, 0x00000014, 0xc00f0000, 
    0x90e40000, 0xa0e40000, 0x00000001, 0xc00f0001, 0xa0000004, 0x00000001, 
    0xe0030000, 0x90e40002, 0x00000001, 0xe0070001, 0x90a90001, 0x00000001, 
    0xe0070002, 0x90a40001, 0x00000001, 0xe0070003, 0x90500001, 0x0000ffff
};
