//
// Generated by Microsoft (R) D3DX9 Shader Assembler 4.09.00.1126
//
//   psa t:\Direct3D Color Grading\shaders\volume texture color grading.1.1.psh
//    /Fht:\Direct3D Color Grading\shaders\volume texture color grading.1.1.psh.h
//    /nologo
//

const DWORD g_ps11_main[] =
{
    0xffff0101, 0x00000042, 0xb00f0000, 0x00000049, 0xb00f0001, 0xb0e40000, 
    0x00000049, 0xb00f0002, 0xb0e40000, 0x0000004a, 0xb00f0003, 0xb0e40000, 
    0x00000001, 0x800f0000, 0xb0e40003, 0x0000ffff
};
