//
// Generated by Microsoft (R) D3DX9 Shader Assembler 4.09.00.1126
//
//   psa t:\Direct3D Color Grading\shaders\volume texture color grading.1.4.psh
//    /Fht:\Direct3D Color Grading\shaders\volume texture color grading.1.4.psh.h
//    /nologo
//

const DWORD g_ps14_main[] =
{
    0xffff0104, 0x00000042, 0x800f0001, 0xb0e40000, 0x0000fffd, 0x00000042, 
    0x800f0000, 0x80e40001, 0x0000ffff
};
